name: Fetch Wildflower Data

on:
  # Run daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual trigger for testing
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode with mock data'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    name: Scrape Plant Data from Wildflower.org
    
    # Explicitly set permissions for security and to allow git push
    permissions:
      contents: write  # Needed to commit and push scraped data
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Run data scraper script
        run: |
          if [ "${{ github.event.inputs.test_mode }}" == "true" ]; then
            echo "Running in test mode with mock data"
            python3 scripts/fetch_wildflower_data.py --test
          else
            echo "Running in normal mode (live data)"
            python3 scripts/fetch_wildflower_data.py
          fi
        continue-on-error: true
      
      - name: Commit and push scraped data
        run: |
          echo "=== Git Configuration and Token Validation ==="
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          echo "Checking GitHub token availability..."
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "WARNING: GITHUB_TOKEN is not set"
          else
            echo "✓ GITHUB_TOKEN is set"
          fi
          
          echo "Checking repository permissions..."
          git remote -v
          
          echo "=== Staging Changes ==="
          git add src/data/wildflower-org/*.json src/data/wildflower-org/fetch_log.txt
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            echo "=== Committing Changes ==="
            CHANGED_FILES=$(git diff --staged --name-only | wc -l)
            echo "Files to commit: $CHANGED_FILES"
            git diff --staged --name-only
            
            git commit -m "Update scraped plant data from wildflower.org"
            
            echo "=== Pushing Changes ==="
            echo "Attempting to push to remote repository..."
            if git push -v; then
              echo "✓ Successfully pushed changes"
            else
              EXIT_CODE=$?
              echo "✗ Failed to push changes (exit code: $EXIT_CODE)"
              echo "This may indicate a permissions issue. Check:"
              echo "  1. Workflow has 'permissions: contents: write'"
              echo "  2. Repository settings allow GitHub Actions to create and approve pull requests"
              echo "  3. Branch protection rules don't block the push"
              exit $EXIT_CODE
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      
      - name: Upload fetch results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: wildflower-data-${{ github.run_number }}
          path: src/data/wildflower-org/
          retention-days: 30
      
      - name: Display log summary
        if: always()
        run: |
          if [ -f src/data/wildflower-org/fetch_log.txt ]; then
            echo "=== Fetch Log Summary ==="
            cat src/data/wildflower-org/fetch_log.txt
          else
            echo "No log file found"
          fi
