name: Scrape Wildflower Data

on:
  # Run on a schedule (weekly on Sundays at 2 AM UTC)
  schedule:
    - cron: '0 2 * * 0'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      scraper:
        description: 'Specific scraper to run (leave empty for all)'
        required: false
        type: choice
        options:
          - ''
          - prairie-moon
          - everwilde
          - trueleaf
          - american-meadows
          - eden-brothers

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: scripts/package.json
      
      - name: Install scraper dependencies
        run: |
          cd scripts
          npm install
      
      - name: Install Chromium for Puppeteer
        run: |
          cd scripts
          npx puppeteer browsers install chrome
      
      - name: Run scrapers
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: false
        run: |
          cd scripts
          if [ -n "${{ github.event.inputs.scraper }}" ]; then
            echo "Running specific scraper: ${{ github.event.inputs.scraper }}"
            npm run scrape:all ${{ github.event.inputs.scraper }}
          else
            echo "Running all scrapers"
            npm run scrape:all
          fi
      
      - name: Check for changes
        id: check_changes
        run: |
          git config --global user.name 'PlantFinder Bot'
          git config --global user.email 'bot@plantfinder.app'
          git add src/data/Plants/*.json
          git add public/images/plants/
          if git diff --staged --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes to commit"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git commit -m "chore: update wildflower data from scrapers [automated]"
          git push
      
      - name: Upload scraping logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraping-logs
          path: scripts/logs/*.json
          retention-days: 30
